name: Deploy Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Serverless + Plugins
        run: |
          npm i -g serverless@3
          npm install --save-dev serverless-offline

      - name: Install Python deps
        working-directory: services/backend
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run unit tests
        working-directory: services/backend
        run: |
          source .venv/bin/activate
          pytest -q

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy backend
        working-directory: services/backend
        env:
          TABLE_NAME: ${{ secrets.TABLE_NAME }}
        run: |
          npx serverless@3 deploy --stage prod
